const LIFE = 'life';

const COUNTRY = {
  US: 'US',
  CA: 'CA'
};

const APPLICANT = {
  PRIMARY: 'primaryInsured',
  SPOUSE: 'spouseInsured'
};

const PREMIUM_MODE = {
  MONTHLY: 1,
  QUARTERLY: 2,
  SEMIANNUAL: 3,
  ANNUAL: 4
};
/**
 * Bank related constants, like routing #, account number,..etc
 */
const BANK = {
  minRoutingNoLength: 9,
  minRoutingNoLengthCA: 8,
  BILLING_TYPE: {
    MONTHLY_DRAFT: 1,
    ANNUAL_DIRECT: 2,
    SEMI_ANNUAL_DIRECT: 3,
    QUARTERLY_DIRECT: 4,
    MONTHLY_GOVT: 5
  },
  PERSON_TYPE: {
    PRIMARY: 1,
    SPOUSE: 2,
    POLICYOWNER: 3,
    OTHER_INDIVIDUAL: 4
  },
  ACCOUNT_TYPE: {
    CHECKING: 1,
    SAVINGS: 0
  },
  BILLING_METHOD: {
    MONTHLY_DRAFT: 1,
    ANNUAL_DIRECT: 2,
    SEMI_ANNUAL_DIRECT: 3,
    QUARTERLY_DIRECT: 4,
    MONTHLY_GOVT: 5
  },
  MGA_STATUS: {
    ACTIVE: 1,
    RETIRED: 2
  },
  MGA_BRANCH: {
    AIRFORCE: 1,
    ARMY: 2,
    COASTGUARD: 3,
    MARINES: 4,
    NAVY: 5
  },
  MGA_PERSON_TYPES: {
    PRIMARY: '1',
    SPOUSE: '2',
    POLICYOWNER: '3',
    OTHER_INDIVIDUAL: '4'
  }
};

const GLOBAL_INFO = 'globalInfo';

const LIFE_STATES = {
  NAME: {
    LIFE_HOME: 'life.home',
    LIFE_LANDING: 'life.landing',
    LIFE_APP: 'life.app',
    /*  GETTING STARTED  */
    ACTIVITY: 'activity',
    CONTACT_LOOKUP: 'life.landing.contactLookup',
    SELECT_CONTACT: 'life.landing.selectContact',
    SELECT_APPLICATION: 'life.landing.selectApplication',
    SELECT_APPLICATION_VALIDATION: 'life.landing.selectApplication.validation',
    PRELIMINARY_QUESTIONS: 'preliminaryQuestions',
    AGENT_INFO: 'agentInfo',
    AGENT_TASKS: 'agentTasks',
    AGENT_PROFILE: 'agentProfile',
    BASESHOP_TRAINEE_LOOKUP: 'life.landing.baseshopTraineeLookup',
    APPLICATION_LOCKED: 'life.landing.applicationLocked',
    APP_STATUS_CHECKLIST: 'life.app.appStatusCheckList',
    FNA_NEEDED: 'fnaNeeded',
    CONTACT_COMPLIANCE: 'life.landing.contactMobileLifeCompliance',

    /*  PERSONAL INFO */
    PRIMARY_INSURED: 'primaryInsured',
    SPOUSE_INSURED: 'spouseInsured',
    POLICY_OWNER_INFO: 'policyOwnerInfo',
    POLICY_SUMMARY: 'life.app.policySummary',
    BENEFICIARY_SUMMARY: 'beneficiarySummary',
    BENEFICIARY_INFO: 'beneficiaryInfo',
    CHILD_SUMMARY: 'childSummary',
    CHILD_INFO: 'childInfo',
    DEF_OF_REPLACEMENT: 'defOfReplacement',
    NOTICE_REG_REPLACEMENT: 'noticeRegReplacement',
    BI_NEEDED: 'biNeeded',
    EXISTING_INSURANCE: 'existingInsurance',
    EXISTING_POLICIES: 'existingPolicies',
    POLICY_DETAILS: 'policyDetails',
    REPLACEMENT_QUESTIONS: 'life.app.replacementQuestions',
    PRIOR_INSURANCE: 'priorInsurance',
    PRIOR_INSURANCE_ACTIVE: 'priorInsuranceActive',
    PRIOR_INSURANCE_TERMINATED: 'priorInsuranceTerminated',
    PRIOR_INSURANCE_POLICYNOTPLACED: 'priorInsurancePolicyNotPlaced',

    /* HEALTH AND COVERAGE STATE DEFINITIONS  */
    ADD_COVERAGE: 'addCoverage',
    FNA_NEEDS_REASON: 'fnaNeedsReason',
    EXISTING_COVERAGE: 'life.app.existingCoverage',
    SUITABILITY_INFO: 'suitabilityInfo',
    MEDICAL_INITIAL: 'life.app.medicalInitial',
    MEDICAL_QUESTION: 'life.app.medicalQuestion',
    MEDICAL_INFO: 'medicalInfo',
    MEDICAL_CHILDREN: 'life.app.medicalChildren',
    MEDICAL_DETAIL: 'life.app.medicalDetail',
    HIV_CONSENT: 'hivConsent',
    UW_REQUIREMENTS: 'underWriting',
    SCHEDULE_PARAMED: 'scheduleParamed',
    BILLING_INFO: 'billing',
    COD_ACKNOWLEDGEMENT: 'codAcknowledgement',

    /* SIGN AND SUBMIT */
    QUICK_CHECK: 'quickCheck',
    SIGNATURE_SUMMARY: 'signatureSummary',
    SIGNATURE_DISCLOSURE_SUMMARY: 'life.app.signatureDisclosureSummary',
    SIGNATURE_DISCLOSURE_SUMMARY_SIGN_PAD:
      'life.app.signatureDisclosureSummary.signPad',
    SIGNATURE_AGENT_DISCLOSURE_SUMMARY:
      'life.app.signatureAgentDisclosureSummary',
    SIGNATURE_AGENT_DISCLOSURE_SUMMARY_SIGN_PAD:
      'life.app.signatureAgentDisclosureSummary.signPad',
    SIGNATURE_DISCLOSURE_SECTIONS: 'life.app.signatureDisclosureSections',
    SIGNATURE_DISCLOSURE_ELECTRONIC_SIGNATURE:
      'life.app.signatureDisclosureSection.signatureDisclosureElectronicSignature',
    SIGNATURE_DISCLOSURE_LIFE_INSURANCE_SALES_ILLUSTRATION_NY:
      'life.app.signatureDisclosureSection.signatureDisclosureNYSalesIllustration',
    SIGNATURE_DISCLOSURE_ELECTRONIC_DELIVERY:
      'life.app.signatureDisclosureSection.signatureDisclosureElectronicDelivery',
    SIGNATURE_DISCLOSURE_CA_SENIORS:
      'life.app.signatureDisclosureSection.signatureDisclosureCaSeniors',
    SIGNATURE_DISCLOSURE_REPLACEMENT_ACK:
      'life.app.signatureDisclosureSection.signatureDisclosureReplacementAck',
    SIGNATURE_DISCLOSURE_HIV_CONSENT_YES:
      'life.app.signatureDisclosureSection.signatureDisclosureHivConsentYes',
    SIGNATURE_DISCLOSURE_HIV_CONSENT_NO:
      'life.app.signatureDisclosureSection.signatureDisclosureHivConsentNo',
    SIGNATURE_DISCLOSURE_HIPAA:
      'life.app.signatureDisclosureSection.signatureDisclosureHipaa',
    SIGNATURE_DISCLOSURE_SUITABILITY_SUMMARY:
      'life.app.signatureDisclosureSection.signatureDisclosureSuitabilitySummary',
    SIGNATURE_DISCLOSURE_APPLICATION_ACK:
      'life.app.signatureDisclosureSection.signatureDisclosureApplicationAck',
    SIGNATURE_DISCLOSURE_FINAL_IMPORTANT_INFO:
      'life.app.signatureDisclosureSection.signatureDisclosureFinalImportantInfo',
    SIGNATURE_DISCLOSURE_PERSONAL_INFO:
      'life.app.signatureDisclosureSection.signatureDisclosurePersonalInfo',
    SIGNATURE_DISCLOSURE_DEFINITION_OF_REPLACEMENT:
      'life.app.signatureDisclosureSection.signatureDisclosureDefinitionOfReplacement',
    SIGNATURE_DISCLOSURE_MEDICAL_CONFIRMATION:
      'life.app.signatureDisclosureSection.signatureDisclosureMedicalConfirmation',
    SIGNATURE_DISCLOSURE_POLICY_DISCLOSURE:
      'life.app.signatureDisclosureSection.signatureDisclosurePolicyDisclosure',
    SIGNATURE_DISCLOSURE_RELINQUISHMENT_OF_OWNERSHIP:
      'life.app.signatureDisclosureSection.signatureDisclosureRelinquishmentOfOwnership',
    SIGNATURE_DISCLOSURE_INDETERMINATE_PREMIUM_DISCLOSURE:
      'life.app.signatureDisclosureSection.signatureDisclosureIndeterminatePremiumDisclosure',
    SIGNATURE_DISCLOSURE_TERMINAL_ILLNESS_BENEFIT:
      'life.app.signatureDisclosureSection.signatureDisclosureTerminalIllnessBenefit',
    SIGNATURE_DISCLOSURE_ADDITIONAL_AGREEMENTS_NY:
      'life.app.signatureDisclosureSection.signatureDisclosureAdditionalAgreements',
    SIGNATURE_AGENT_COMMENTS: 'life.app.signatureDisclosureAgentComments',
    PRIMARY_SIGNATURE: 'primarySignature',
    SPOUSE_SIGNATURE: 'spouseSignature',
    POLICY_OWNER_SIGNATURE: 'life.app.policyOwnerSignature',
    AGENT_SIGNATURE: 'agentSignature',
    AGENT_ACKNOWLEDGEMENT: 'life.app.agentAcknowledgment',
    AGENT_COMMENTS: 'life.app.agentComments',
    SUBMIT_APPLICATION: 'submitApp',
    UNLOCK_APPLICATION: 'unlockApp',
    CONGRATULATIONS: 'congratulations'
  }
};

//TODO: add the rest of these
const PAGE_ID_MAP = {
  100: LIFE_STATES.NAME.PRELIMINARY_QUESTIONS,
  105: LIFE_STATES.NAME.AGENT_INFO,
  110: LIFE_STATES.NAME.PRIMARY_INSURED,
  115: LIFE_STATES.NAME.SPOUSE_INSURED,
  120: LIFE_STATES.NAME.POLICY_OWNER_INFO,
  125: LIFE_STATES.NAME.CHILD_SUMMARY,
  130: LIFE_STATES.NAME.CHILD_INFO, // ! verify
  135: LIFE_STATES.NAME.BENEFICIARY_INFO, // Beneficiary Summary
  140: LIFE_STATES.NAME.BENEFICIARY_INFO,
  142: LIFE_STATES.NAME.AGENT_TASKS,
  143: LIFE_STATES.NAME.FNA_NEEDED,
  145: LIFE_STATES.NAME.EXISTING_INSURANCE,
  150: LIFE_STATES.NAME.EXISTING_POLICIES,
  // 155: LIFE_STATES.NAME.EXISTING_POLICIES, // life.app.policyInfo
  160: LIFE_STATES.NAME.DEF_OF_REPLACEMENT,
  // 165:   Previously Additional Information, now Primary/Spouse
  // 170: LIFE_STATES.NAME.DEF_OF_REPLACEMENT, // Insurance Class and Products
  175: LIFE_STATES.NAME.BILLING_INFO,
  180: LIFE_STATES.NAME.BILLING_INFO,
  185: LIFE_STATES.NAME.PRIOR_INSURANCE,
  190: LIFE_STATES.NAME.SCHEDULE_PARAMED,
  201: LIFE_STATES.NAME.HIV_CONSENT,
  202: LIFE_STATES.NAME.ADD_COVERAGE,
  203: LIFE_STATES.NAME.ADD_COVERAGE,
  204: LIFE_STATES.NAME.ADD_COVERAGE,
  205: LIFE_STATES.NAME.ADD_COVERAGE,
  400: LIFE_STATES.NAME.MEDICAL_INFO,
  401: LIFE_STATES.NAME.MEDICAL_INFO,
  402: LIFE_STATES.NAME.MEDICAL_INFO,
  403: LIFE_STATES.NAME.MEDICAL_INFO,
  404: LIFE_STATES.NAME.MEDICAL_INFO,
  405: LIFE_STATES.NAME.COD_ACKNOWLEDGEMENT,
  406: LIFE_STATES.NAME.SUITABILITY_INFO
};

export const NEXT_VIEW_STATE_MAP = {
  [LIFE_STATES.NAME.PRELIMINARY_QUESTIONS]: LIFE_STATES.NAME.AGENT_INFO,
  [LIFE_STATES.NAME.AGENT_INFO]: LIFE_STATES.NAME.FNA_NEEDED,
  [LIFE_STATES.NAME.FNA_NEEDED]: LIFE_STATES.NAME.AGENT_TASKS,
  [LIFE_STATES.NAME.AGENT_TASKS]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.PRIMARY_INSURED]: LIFE_STATES.NAME.SPOUSE_INSURED,
  [LIFE_STATES.NAME.SPOUSE_INSURED]: LIFE_STATES.NAME.CHILD_SUMMARY,
  [LIFE_STATES.NAME.CHILD_SUMMARY]: LIFE_STATES.NAME.POLICY_OWNER_INFO,
  [LIFE_STATES.NAME.POLICY_OWNER_INFO]: LIFE_STATES.NAME.BENEFICIARY_INFO,
  [LIFE_STATES.NAME.BENEFICIARY_INFO]: LIFE_STATES.NAME.DEF_OF_REPLACEMENT,
  [LIFE_STATES.NAME.DEF_OF_REPLACEMENT]:
    LIFE_STATES.NAME.NOTICE_REG_REPLACEMENT,
  [LIFE_STATES.NAME.NOTICE_REG_REPLACEMENT]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_ACTIVE,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_ACTIVE]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_TERMINATED,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_TERMINATED]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_POLICYNOTPLACED,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_POLICYNOTPLACED]:
    LIFE_STATES.NAME.EXISTING_INSURANCE,
  [LIFE_STATES.NAME.EXISTING_INSURANCE]: LIFE_STATES.NAME.EXISTING_POLICIES,
  [LIFE_STATES.NAME.EXISTING_POLICIES]: LIFE_STATES.NAME.BI_NEEDED,
  [LIFE_STATES.NAME.BI_NEEDED]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.SUITABILITY_INFO]: LIFE_STATES.NAME.MEDICAL_INFO,
  [LIFE_STATES.NAME.MEDICAL_INFO]: LIFE_STATES.NAME.ADD_COVERAGE,
  [LIFE_STATES.NAME.ADD_COVERAGE]: LIFE_STATES.NAME.FNA_NEEDS_REASON,
  [LIFE_STATES.NAME.FNA_NEEDS_REASON]: LIFE_STATES.NAME.UW_REQUIREMENTS,
  [LIFE_STATES.NAME.UW_REQUIREMENTS]: LIFE_STATES.NAME.HIV_CONSENT,
  [LIFE_STATES.NAME.HIV_CONSENT]: LIFE_STATES.NAME.SCHEDULE_PARAMED,
  [LIFE_STATES.NAME.SCHEDULE_PARAMED]: LIFE_STATES.NAME.COD_ACKNOWLEDGEMENT,
  [LIFE_STATES.NAME.COD_ACKNOWLEDGEMENT]: LIFE_STATES.NAME.BILLING_INFO,
  [LIFE_STATES.NAME.BILLING_INFO]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.QUICK_CHECK]: LIFE_STATES.NAME.SIGNATURE_SUMMARY,
  [LIFE_STATES.NAME.SIGNATURE_SUMMARY]: LIFE_STATES.NAME.PRIMARY_SIGNATURE,
  [LIFE_STATES.NAME.PRIMARY_SIGNATURE]: LIFE_STATES.NAME.SPOUSE_SIGNATURE,
  [LIFE_STATES.NAME.SPOUSE_SIGNATURE]: LIFE_STATES.NAME.AGENT_SIGNATURE,
  [LIFE_STATES.NAME.AGENT_SIGNATURE]: LIFE_STATES.NAME.SUBMIT_APPLICATION,
  [LIFE_STATES.NAME.SUBMIT_APPLICATION]: LIFE_STATES.NAME.CONGRATULATIONS,
  [LIFE_STATES.NAME.CONGRATULATIONS]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST
};

export const PREVIOUS_VIEW_STATE_MAP = {
  [LIFE_STATES.NAME.PRELIMINARY_QUESTIONS]:
    LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.AGENT_INFO]: LIFE_STATES.NAME.PRELIMINARY_QUESTIONS,
  [LIFE_STATES.NAME.FNA_NEEDED]: LIFE_STATES.NAME.AGENT_INFO,
  [LIFE_STATES.NAME.AGENT_TASKS]: LIFE_STATES.NAME.FNA_NEEDED,
  [LIFE_STATES.NAME.PRIMARY_INSURED]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.SPOUSE_INSURED]: LIFE_STATES.NAME.PRIMARY_INSURED,
  [LIFE_STATES.NAME.CHILD_SUMMARY]: LIFE_STATES.NAME.SPOUSE_INSURED,
  [LIFE_STATES.NAME.POLICY_OWNER_INFO]: LIFE_STATES.NAME.CHILD_SUMMARY,
  [LIFE_STATES.NAME.BENEFICIARY_INFO]: LIFE_STATES.NAME.POLICY_OWNER_INFO,
  [LIFE_STATES.NAME.DEF_OF_REPLACEMENT]: LIFE_STATES.NAME.BENEFICIARY_INFO,
  [LIFE_STATES.NAME.NOTICE_REG_REPLACEMENT]:
    LIFE_STATES.NAME.DEF_OF_REPLACEMENT,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_ACTIVE]:
    LIFE_STATES.NAME.NOTICE_REG_REPLACEMENT,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_TERMINATED]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_ACTIVE,
  [LIFE_STATES.NAME.PRIOR_INSURANCE_POLICYNOTPLACED]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_TERMINATED,
  [LIFE_STATES.NAME.EXISTING_INSURANCE]:
    LIFE_STATES.NAME.PRIOR_INSURANCE_POLICYNOTPLACED,
  [LIFE_STATES.NAME.EXISTING_POLICIES]: LIFE_STATES.NAME.EXISTING_INSURANCE,
  [LIFE_STATES.NAME.BI_NEEDED]: LIFE_STATES.NAME.EXISTING_POLICIES,
  [LIFE_STATES.NAME.SUITABILITY_INFO]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.MEDICAL_INFO]: LIFE_STATES.NAME.SUITABILITY_INFO,
  [LIFE_STATES.NAME.ADD_COVERAGE]: LIFE_STATES.NAME.MEDICAL_INFO,
  [LIFE_STATES.NAME.FNA_NEEDS_REASON]: LIFE_STATES.NAME.ADD_COVERAGE,
  [LIFE_STATES.NAME.UW_REQUIREMENTS]: LIFE_STATES.NAME.FNA_NEEDS_REASON,
  [LIFE_STATES.NAME.HIV_CONSENT]: LIFE_STATES.NAME.UW_REQUIREMENTS,
  [LIFE_STATES.NAME.SCHEDULE_PARAMED]: LIFE_STATES.NAME.HIV_CONSENT,
  [LIFE_STATES.NAME.COD_ACKNOWLEDGEMENT]: LIFE_STATES.NAME.SCHEDULE_PARAMED,
  [LIFE_STATES.NAME.BILLING_INFO]: LIFE_STATES.NAME.COD_ACKNOWLEDGEMENT,
  [LIFE_STATES.NAME.QUICK_CHECK]: LIFE_STATES.NAME.APP_STATUS_CHECKLIST,
  [LIFE_STATES.NAME.SIGNATURE_SUMMARY]: LIFE_STATES.NAME.QUICK_CHECK,
  [LIFE_STATES.NAME.PRIMARY_SIGNATURE]: LIFE_STATES.NAME.SIGNATURE_SUMMARY,
  [LIFE_STATES.NAME.SPOUSE_SIGNATURE]: LIFE_STATES.NAME.PRIMARY_SIGNATURE,
  [LIFE_STATES.NAME.AGENT_SIGNATURE]: LIFE_STATES.NAME.SPOUSE_SIGNATURE,
  [LIFE_STATES.NAME.SUBMIT_APPLICATION]: LIFE_STATES.NAME.AGENT_SIGNATURE,
  [LIFE_STATES.NAME.CONGRATULATIONS]: LIFE_STATES.NAME.SUBMIT_APPLICATION
};

const SYSTEM_VIEWS = {
  SESSION: 'session',
  PAGE_NOT_FOUND: 'pageNotFound',
  SHARED_COMPONENTS: 'sharedComponents'
};

const APP_STATUS = {
  PRACTICE: 99,
  INCOMPLETE: 0,
  COMPLETE: 1,
  SUBMITTED_BUT_NOT_IN_DB2: 2,
  SUBMITTED: 3,
  DUPLICATE: 9,
  TEMP_LOAD_BALANCE: -2,
  ERROR_LOADING_TO_DB2: -1
};

export {
  APPLICANT,
  APP_STATUS,
  LIFE_STATES,
  COUNTRY,
  PREMIUM_MODE,
  BANK,
  LIFE,
  SYSTEM_VIEWS,
  PAGE_ID_MAP,
  GLOBAL_INFO
};
